[workspace]
resolver = "2"
members = ["prover", "sdk", "crates/podman", "crates/utils", "crates/common"]

[workspace.package]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
podman = { path = "crates/podman" }
prover = { path = "prover" }
common = { path = "crates/common" }

axum = { version = "0.7.5", features = ["http2", "macros", "multipart", "ws"] }

async-session = "3.0.0"
cairo-proof-parser = { git = "https://github.com/cartridge-gg/cairo-proof-parser.git" }
clap = { version = "4.5.4", features = ["derive", "env"] }

thiserror = "1.0.59"
utils = { path = "crates/utils" }
tokio = { version = "1.37.0", features = ["full"] }
tower-http = { version = "0.5.2", features = [
    "timeout",
    "trace",
    "decompression-br",
    "set-header",
] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
hex = "0.4.3"
serde_with = "=1.6.1"
bytes = "1.4.0"
hyper-util = "0.1.3"
http = "1.1.0"
reqwest = { version = "0.12.4", features = ["blocking", "json"] }
rand = "0.8.5"
ed25519-dalek = { version = "2.1.1", features = ["rand_core", "serde"] }
reqwest_cookie_store = "0.7.0"
url = "2.5.0"
