[package]
name = "cairo-prove"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
ed25519-dalek.workspace = true
prefix-hex.workspace = true
prover-sdk.workspace = true
tokio.workspace = true
url.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
prover.workspace = true
cairo-proof-parser.workspace = true
