apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prover.yaml
  - routes.yaml

configMapGenerator:
  - name: config
    envs:
      - .env.local
      
secretGenerator:
  - name: secret
    envs:
      - .env