apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prover
spec:
  parentRefs:
    - kind: Gateway
      name: nginx
      namespace: nginx-gateway
  hostnames:
    - prover.visoft.dev
  rules:
    - matches:
      backendRefs:
        - name: prover
          port: 80