[package]
name = "prover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common.workspace = true

axum.workspace = true
clap.workspace = true
podman.workspace = true
thiserror.workspace = true
utils.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
rand = "0.8.5"
bytes = "1.4.0"
serde_with = "3.2.0"
prefix-hex = "0.7.1"
lazy_static = "1.4.0"
curve25519-dalek = "4"
ed25519-dalek = "2.1.1"
hex = "0.4"
jsonwebtoken = "9"
chrono = "0.4.38"
once_cell = "1.19.0"
