[package]
name = "common"
version.workspace = true
edition.workspace = true

[dependencies]
hex.workspace = true
serde.workspace = true
serde_with.workspace = true
serde_json.workspace = true
ed25519-dalek.workspace = true
