[package]
name = "register"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
ed25519-dalek.workspace = true
prefix-hex.workspace = true
prover-sdk.workspace = true
tokio.workspace = true
url.workspace = true
