[package]
name = "prove"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
ed25519-dalek.workspace = true
sdk.workspace = true
prefix-hex.workspace = true
tokio.workspace = true
url.workspace = true
serde.workspace = true
serde_json.workspace = true
