[package]
name = "prover-utils"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
ed25519-dalek.workspace = true
hex.workspace = true
sdk.workspace = true
tokio.workspace = true
url.workspace = true
