name: ci
on: push
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - name: Prepare
        shell: bash
        run: |
          sh scripts/0-venv.sh
          sh scripts/1-compile.sh
          sh scripts/2-merge.sh
          ls -Rl examples/
      - name: Build
        run: cargo build --verbose
      - name: Run prover
        run: |
          cargo run -p prover -- --jwt-secret-key "asdf" --authorized-keys "0xd16b71c90dbf897e5964d2f267d04664b3c035036559d712994739ea6cf2fd9f" --message-expiration-time 60 --session-expiration-time 3600 &
          sleep 5
      - name: Run tests
        run: cargo test --workspace --verbose
